src/Entity/Product.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
final class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $sku;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private float $cost;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private float $price;

    /**
     * @ORM\Column(type="integer")
     */
    private int $qty;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSku(): string
    {
        return $this->sku;
    }

    public function setSku(string $sku): self
    {
        $this->sku = $sku;

        return $this;
    }

    public function getCost(): float
    {
        return $this->cost;
    }

    public function setCost(float $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getPrice(): float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQty(): int
    {
        return $this->qty;
    }

    public function setQty(int $qty): self
    {
        $this->qty = $qty;

        return $this;
    }

    public function getProfit(): float
    {
        return $this->price - $this->cost;
    }

    public function getROI(): float
    {
        return $this->getProfit() * $this->qty;
    }
}

src/Controller/HomeController.php
<?php declare(strict_types=1);

namespace App\Controller;

use App\Entity\Product;
use App\Repository\ProductRepository;
use App\Service\CsvParser;
use App\Service\CurrencyConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Constraints\File;

final class HomeController extends AbstractController
{
    public function index(CurrencyConverter $currencyConverter): Response
    {
        $form = $this->createFormBuilder()
            ->add('products', FileType::class, [
                'label' => 'Product Form',
                'mapped' => false,
                'constraints' => new File(
                    maxSize: '8m',
                    mimeTypes: ['application/csv'],
                    mimeTypesMessage: 'Please upload a valid CSV document',
                ),
                'attr' => ['class' => 'form-control-file'],
            ])
            ->add('submit', SubmitType::class, [
                'attr' => ['class' => 'btn btn-primary'],
            ])
            ->getForm();

        /** @var ProductRepository $em */
        $em = $this->getDoctrine()->getRepository(Product::class);

        return $this->renderForm('index.html.twig', [
            'form' => $form,
            'products' => $em->findAll(),
            'avg_cost' => $em->avgCost(),
            'avg_price' => $em->avgPrice(),
            'total_qty' => $em->totalQty(),
            'average_profit_margin' => $em->avgProfitMargin(),
            'total_profit' => $em->totalProfit(),
            'cad_ratio' => $currencyConverter->getRatio('USD', 'CAD'),
        ]);
    }

    public function store(Request $request)
    {
        /** @var UploadedFile $file */
        $file = $request->files->get('form')['products'];

        $em = $this->getDoctrine()->getManager();
        $em->getRepository(Product::class)->truncate();

        foreach ((new CsvParser($file))->parse('sku', 'cost', 'price', 'qty') as ['sku' => $sku, 'cost' => $cost, 'price' => $price, 'qty' => $qty]) {
            $em->persist(
                (new Product())
                    ->setSku($sku)
                    ->setCost((float)$cost)
                    ->setPrice((float)$price)
                    ->setQty((int)$qty)
            );
        }

        $em->flush();

        return $this->redirectToRoute('index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
        {% endblock %}

        {% block javascripts %}
            <script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.bundle.min.js"></script>
        {% endblock %}
    </head>
    <body>
        <div class="c-wrapper c-fixed-components">
            <div class="c-body">
                <main class="c-main">
                    <div class="container-fluid">
                        {% block body %}{% endblock %}
                    </div>
                </main>
            </div>
        </div>
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        td.positive {color: green;}
        td.negative {color: red;}
    </style>
{% endblock %}

{% block body %}
    <h1>File Processor</h1>

    <p>Submit your CSV file then the table will populate.</p>
    <p>If you submit a new file, existing stored data will be truncated.</p>

    <div id="the-form">
        {{ form_start(form) }}
        {% if not form.vars.valid %}
        <div class="alert alert-danger" role="alert">
            {{ form_errors(form) }}
        </div>
        {% endif %}

        <div class="form-group">
            {{ form_label(form.products) }}
            {{ form_widget(form.products) }}
        </div>

        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>
        {{ form_end(form) }}
    </div>

    <hr>

    <div id="the-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>SKU</th>
                <th>Cost</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Profit</th>
                <th>ROI</th>
                <th>ROI (CAD)</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.sku }}</td>
                <td>{{ product.cost|format_currency('USD') }}</td>
                <td>{{ product.price|format_currency('USD') }}</td>
                <td class="{{ product.qty > 0 ? "positive" : "negative" }}">{{ product.qty }}</td>
                <td class="{{ product.profit > 0 ? "positive" : "negative" }}">{{ product.profit|format_currency('USD') }}</td>
                <td class="{{ product.roi > 0 ? "positive" : "negative" }}">{{ product.roi|format_currency('USD') }}</td>
                <td class="{{ product.roi > 0 ? "positive" : "negative" }}">{{ (product.roi * cad_ratio)|format_currency('USD') }}</td>
            </tr>
            {% else %}
            <tr>
                <td colspan="7">No products found!</td>
            </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th>Summary</th>
                <th>Avg Cost: {{ avg_cost|format_currency('USD') }}</th>
                <th>Avg Price: {{ avg_price|format_currency('USD') }}</th>
                <th>Total Qty: {{ total_qty }}</th>
                <th>Avg Profit: {{ average_profit_margin|format_currency('USD') }}</th>
                <th>Total Profit: {{ total_profit|format_currency('USD') }}</th>
                <th>Total Profit (CAD): {{ (total_profit * cad_ratio)|format_currency('USD') }}</th>
            </tr>
            </tfoot>
        </table>
    </div>
{% endblock %}